apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-python-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devops-python-api
  template:    
    metadata:
      labels:
        app: devops-python-api
    spec:
      containers:
        - name: devops-python-api
          image: ghcr.io/mumincandurak/devops-python-api:latest
          ports:
            - containerPort: 8000  
          env:
            - name: APP_NAME 
              valueFrom:
                configMapKeyRef:
                  name: devops-python-api-config
                  key: APP_NAME
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 8
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 8
            periodSeconds: 10            